IF DEF(_09_29)
UtilityGarbage:
	db $FF, $81, $FD, $EB, $E7, $EF, $DF, $FF, $FF, $FB, $F7, $E7, $97, $F7, $F7, $FF
	db $FF, $EF, $81, $BD, $FD, $FB, $E7, $FF, $FF, $83, $EF, $EF, $EF, $EF, $83, $FF
	db $FF, $FB, $81, $F3, $EB, $DB, $BB, $FF, $FF, $DF, $81, $DD, $DD, $DD, $BB, $FF
	db $FF, $EF, $81, $EF, $81, $F7, $F7, $FF, $FF, $C1, $DD, $BD, $FD, $FB, $C7, $FF
	db $FF, $DF, $C1, $DB, $BB, $FB, $E7, $FF, $FF, $FF, $81, $FD, $FD, $FD, $81, $FF
	db $FF, $DB, $81, $DB, $DB, $FB, $C7, $FF, $FF, $8F, $FD, $8D, $FD, $FB, $87, $FF
	db $FF, $81, $FB, $F7, $E7, $DB, $BD, $FF, $FF, $DF, $81, $DD, $DB, $DF, $E3, $FF
	db $FF, $BD, $BD, $DD, $FB, $FB, $E7, $FF, $FF, $C1, $DD, $C1, $BD, $FB, $E7, $FF
	db $FF, $F9, $C7, $F7, $81, $F7, $CF, $FF, $FF, $AF, $AD, $AD, $FD, $FB, $C7, $FF
	db $FF, $C3, $FF, $81, $F7, $F7, $CF, $FF, $FF, $DF, $DF, $C7, $D9, $DF, $DF, $FF
	db $FF, $F7, $81, $F7, $F7, $F7, $CF, $FF, $FF, $FF, $C3, $FF, $FF, $FF, $81, $FF
	db $FF, $81, $FD, $EB, $F7, $EB, $9D, $FF, $FF, $EF, $81, $FB, $E7, $89, $EF, $FF
	db $FF, $FD, $FD, $FB, $FB, $F7, $CF, $FF, $FF, $FF, $DB, $DB, $DB, $BD, $BD, $FF
	db $FF, $BF, $B3, $8F, $BF, $BF, $C1, $FF, $FF, $FF, $81, $FD, $FD, $FB, $E7, $FF
	db $FF, $FF, $EF, $D7, $BB, $FD, $FF, $FF, $FF, $EF, $81, $EF, $AB, $AD, $AD, $FF
	db $FF, $81, $FD, $DB, $E7, $F7, $FB, $FF, $FF, $C3, $FF, $C3, $FF, $8F, $F1, $FF
	db $FF, $EF, $EF, $DB, $DB, $B1, $8D, $FF, $FF, $F7, $D7, $E7, $F3, $ED, $9F, $FF
	db $FF, $C3, $EF, $81, $EF, $EF, $F3, $FF, $FF, $DF, $81, $DD, $DB, $EF, $EF, $FF
	db $FF, $C3, $FB, $FB, $FB, $FB, $81, $FF, $FF, $81, $FD, $81, $FD, $FD, $81, $FF
	db $FF, $C3, $FF, $81, $FD, $FB, $E7, $FF, $FF, $BD, $BD, $BD, $FD, $FB, $E7, $FF
	db $FF, $D7, $D7, $D7, $D7, $D5, $B3, $FF, $FF, $BF, $BF, $BF, $BD, $B3, $8F, $FF
	db $FF, $81, $BD, $BD, $BD, $BD, $81, $FF, $FF, $81, $BD, $FD, $FD, $FB, $C7, $FF
	db $FF, $81, $FD, $C1, $FD, $FB, $C7, $FF, $FF, $9F, $ED, $FD, $FB, $F7, $8F, $FF
	db $FA, $DA, $81, $DD, $DD, $DD, $BB, $FF, $FA, $EA, $81, $EF, $81, $F7, $F7, $FF
	db $FA, $C2, $DD, $BD, $FD, $FB, $C7, $FF, $FA, $DA, $C1, $DB, $BB, $FB, $E7, $FF
	db $FA, $FA, $81, $FD, $FD, $FD, $81, $FF, $FA, $DE, $81, $DB, $FB, $FB, $C7, $FF
	db $FA, $8A, $FD, $8D, $FD, $FB, $87, $FF, $FA, $82, $FB, $F7, $E7, $DB, $BD, $FF
	db $FA, $DA, $81, $DD, $DB, $DF, $E3, $FF, $FA, $BA, $BD, $DD, $FB, $FB, $E7, $FF
	db $FA, $C2, $DD, $C1, $BD, $FB, $E7, $FF, $FA, $FA, $C7, $F7, $81, $F7, $CF, $FF
	db $FA, $AA, $AD, $AD, $FD, $FB, $C7, $FF, $FA, $C2, $FF, $81, $F7, $F7, $CF, $FF
	db $FA, $DA, $DF, $C7, $D9, $DF, $DF, $FF, $FA, $FA, $DF, $DB, $DB, $BD, $BD, $FF
	db $FA, $BA, $B3, $8F, $BF, $BF, $C1, $FF, $FA, $FA, $81, $FD, $FD, $FB, $E7, $FF
	db $FA, $FA, $EF, $D7, $BB, $FD, $FF, $FF, $FA, $EA, $81, $EF, $AB, $AD, $AD, $FF
	db $FD, $FA, $DD, $DB, $DB, $BD, $BD, $FF, $FD, $BA, $B5, $8F, $BF, $BF, $C1, $FF
	db $FD, $FA, $81, $FD, $FD, $FB, $E7, $FF, $FD, $FA, $ED, $D7, $BB, $FD, $FF, $FF
	db $FD, $EA, $85, $EF, $AB, $AD, $AD, $FF, $FF, $FF, $87, $F7, $CF, $DF, $BF, $FF
	db $FF, $FF, $FF, $F7, $8F, $EF, $EF, $FF, $FF, $FF, $DF, $87, $B7, $F7, $CF, $FF
	db $FF, $FF, $FF, $8F, $DF, $DF, $8F, $FF, $FF, $FF, $EF, $87, $CF, $AF, $EF, $FF
	db $FF, $FF, $DF, $87, $D7, $DF, $DF, $FF, $FF, $FF, $FF, $8F, $EF, $EF, $87, $FF
	db $FF, $FF, $8F, $EF, $8F, $EF, $8F, $FF, $FF, $FF, $FF, $AF, $AB, $FB, $C7, $FF
	db $FF, $C3, $BD, $BD, $BD, $BD, $C3, $FF, $FF, $F7, $E7, $F7, $F7, $F7, $F7, $FF
	db $FF, $C3, $BD, $FB, $E7, $DF, $81, $FF, $FF, $C3, $BD, $E3, $FD, $BD, $C3, $FF
	db $FF, $F3, $EB, $DB, $BB, $81, $FB, $FF, $FF, $81, $BF, $83, $FD, $FD, $83, $FF
	db $FF, $C3, $BF, $83, $BD, $BD, $C3, $FF, $FF, $81, $FD, $FB, $FB, $F7, $F7, $FF
	db $FF, $C3, $BD, $C3, $BD, $BD, $C3, $FF, $FF, $C3, $BD, $BD, $C1, $FD, $C3, $FF
	db $FF, $E7, $DB, $DB, $BD, $81, $BD, $FF, $FF, $83, $BD, $83, $BD, $BD, $83, $FF
	db $FF, $C3, $BD, $BF, $BF, $BD, $C3, $FF, $FF, $8F, $B3, $BD, $BD, $B3, $8F, $FF
	db $FF, $81, $BF, $81, $BF, $BF, $81, $FF, $FF, $81, $BF, $81, $BF, $BF, $BF, $FF
	db $FF, $C1, $BF, $B1, $BD, $BD, $C1, $FF, $FF, $BD, $BD, $81, $BD, $BD, $BD, $FF
	db $FF, $C7, $EF, $EF, $EF, $EF, $C7, $FF, $FF, $E1, $FB, $FB, $FB, $BB, $C7, $FF
	db $FF, $B9, $A7, $8F, $B7, $BB, $BD, $FF, $FF, $BF, $BF, $BF, $BF, $BF, $81, $FF
	db $FF, $BD, $99, $A5, $BD, $BD, $BD, $FF, $FF, $BD, $9D, $AD, $B5, $B9, $BD, $FF
	db $FF, $C3, $BD, $BD, $BD, $BD, $C3, $FF, $FF, $83, $BD, $BD, $83, $BF, $BF, $FF
	db $FF, $C3, $BD, $BD, $B5, $BB, $C5, $FF, $FF, $83, $BD, $BD, $83, $BB, $BD, $FF
	db $FF, $C1, $BF, $C3, $FD, $BD, $C3, $FF, $FF, $83, $EF, $EF, $EF, $EF, $EF, $FF
	db $FF, $BD, $BD, $BD, $BD, $BD, $C3, $FF, $FF, $BD, $BD, $DB, $DB, $E7, $E7, $FF
	db $FF, $BD, $AD, $AD, $AD, $AD, $D3, $FF, $FF, $BD, $DB, $E7, $E7, $DB, $BD, $FF
	db $FF, $BB, $BB, $D7, $EF, $EF, $EF, $FF, $FF, $81, $FB, $F7, $EF, $DF, $81, $FF
	db $EF, $C7, $AB, $EF, $C7, $BB, $BB, $C7, $C7, $BB, $BB, $C7, $EF, $83, $EF, $EF
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
	db $00, $00, $00, $00, $00, $00, $00, $00, $FF, $FF, $FF, $FF, $81, $FF, $FF, $FF
	db $FF, $CF, $C7, $C3, $C1, $C3, $C7, $CF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
ENDC
